name: Harmony Run
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4'

      - name: Set PGURI as an environment variable
        run: echo "PGURI=${{ secrets.PGURI }}" >> $GITHUB_ENV

      - name: Start backend
        working-directory: backend
        env:
          DATABASE_PASSWORD: ${{ secrets.PGURI }}
        run: |
          npm install
          npm run build
          npm run start

      - name: Start frontend
        working-directory: frontend
        run: |
          npm install
          npm run dev
          npx cypress open
