on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set PGURI as an environment variable
        run: echo "PGURI=${{ secrets.PGURI }}" >> $GITHUB_ENV

      - name: create env file
        run: |
         touch .env
         echo ${{ secrets.PGURI }} >> .env
        
      - name: Start backend
        env:
          PGURI: ${{ secrets.PGURI }}
        run: |
          cd backend
          npm install
          npm run build
          npm start &
          cd ..

      - name: Start frontend
        run: |
         cd frontend
         npm install
         pm run dev -- --port 3001 &
   

      - name: Run Cypress E2E tests
        working-directory: frontend
        run: npm run cy:run-e2e

      - name: Run Cypress unit tests
        working-directory: frontend
        run: npm run cy:run-unit
      
