on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set PGURI as an environment variable
        run: echo "PGURI=postgres://harmony_run_edes_user:HaTigyxsqZtOStRzmhBNl3Z5bf32FM8M@dpg-cltd3ida73kc73eh2eag-a.frankfurt-postgres.render.com/harmony_run_edes?sslmode=require" >> $GITHUB_ENV

      - name: Debug PGURI
        run: |
          echo "PGURI: ${{ env.PGURI }}"
        
      - name: Start backend
        working-directory: backend
        env:
          PGURI: ${{ secrets.PGURI }}
        run: |
          echo "PGURI: $PGURI"
          npm install
          npm run build
          npm run start

      - name: Start frontend
        working-directory: frontend
        run: |
          npm install
          npm run dev
          npx cypress open
