on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set PGURI as an environment variable
        run: echo "PGURI=${{ secrets.PGURI }}" >> $GITHUB_ENV
        

      - name: Start backend
        working-directory: backend
        env:
          PGURI: ${{ secrets.PGURI }}
        run: |
          npm install
          npm run build
          npm run start

      - name: Start frontend
        working-directory: frontend
        run: |
          npm install
          npm run dev
          npx cypress open
